# Changes here will be overwritten by Copier
_commit: 55f9353
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: t.paine154@gmail.com
github: tkp-aliases
project_description: Alais for fsspec-layer
project_name: layer-fsspec
python_version_primary: '3.11'
team: the layer-fsspec authors
